<?php

require_once 'DeepCopy/autoload.php';
require_once 'PharIo/Manifest/autoload.php';
// require_once 'PharIo/Version/autoload.php'; (already required by PharIo/Manifest)
require_once 'Prophecy/autoload.php';
require_once 'SebastianBergmann/CodeCoverage/autoload.php';
// require_once 'File/Iterator/Autoload.php'; (already required by CodeCoverage >= 2.0.15)
// require_once 'Text/Template/Autoload.php'; (already required by phpunit-mock-object >= 2.3 and CodeCoverage >= 2.0.15)
require_once 'PHP/Timer/Autoload.php';
require_once 'PHPUnit/Framework/MockObject/Autoload.php';
// require_once 'SebastianBergmann/Comparator/autoload.php'; (already required by Prophecy)
// require_once 'SebastianBergmann/Diff/autoload.php'; (already required by Comparator >= 1.1)
// require_once 'SebastianBergmann/Environment/autoload.php'; (already required by CodeCoverage >= 2.0.15)
// require_once 'SebastianBergmann/Exporter/autoload.php'; (already required by Comparator >= 1.1)
require_once 'SebastianBergmann/GlobalState/autoload.php';
require_once 'SebastianBergmann/ObjectEnumerator/autoload.php';
require_once 'SebastianBergmann/ResourceOperations/autoload.php';
// require_once 'SebastianBergmann/Version/autoload.php'; (already required by CodeCoverage >= 2.0.15)


// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'phpunit\\exception' => '/Exception.php',
                'phpunit\\framework\\assert' => '/Framework/Assert.php',
                'phpunit\\framework\\assertionfailederror' => '/Framework/AssertionFailedError.php',
                'phpunit\\framework\\basetestlistener' => '/Framework/BaseTestListener.php',
                'phpunit\\framework\\codecoverageexception' => '/Framework/CodeCoverageException.php',
                'phpunit\\framework\\constraint\\arrayhaskey' => '/Framework/Constraint/ArrayHasKey.php',
                'phpunit\\framework\\constraint\\arraysubset' => '/Framework/Constraint/ArraySubset.php',
                'phpunit\\framework\\constraint\\attribute' => '/Framework/Constraint/Attribute.php',
                'phpunit\\framework\\constraint\\callback' => '/Framework/Constraint/Callback.php',
                'phpunit\\framework\\constraint\\classhasattribute' => '/Framework/Constraint/ClassHasAttribute.php',
                'phpunit\\framework\\constraint\\classhasstaticattribute' => '/Framework/Constraint/ClassHasStaticAttribute.php',
                'phpunit\\framework\\constraint\\composite' => '/Framework/Constraint/Composite.php',
                'phpunit\\framework\\constraint\\constraint' => '/Framework/Constraint/Constraint.php',
                'phpunit\\framework\\constraint\\count' => '/Framework/Constraint/Count.php',
                'phpunit\\framework\\constraint\\directoryexists' => '/Framework/Constraint/DirectoryExists.php',
                'phpunit\\framework\\constraint\\exception' => '/Framework/Constraint/Exception.php',
                'phpunit\\framework\\constraint\\exceptioncode' => '/Framework/Constraint/ExceptionCode.php',
                'phpunit\\framework\\constraint\\exceptionmessage' => '/Framework/Constraint/ExceptionMessage.php',
                'phpunit\\framework\\constraint\\exceptionmessageregularexpression' => '/Framework/Constraint/ExceptionMessageRegularExpression.php',
                'phpunit\\framework\\constraint\\fileexists' => '/Framework/Constraint/FileExists.php',
                'phpunit\\framework\\constraint\\greaterthan' => '/Framework/Constraint/GreaterThan.php',
                'phpunit\\framework\\constraint\\isanything' => '/Framework/Constraint/IsAnything.php',
                'phpunit\\framework\\constraint\\isempty' => '/Framework/Constraint/IsEmpty.php',
                'phpunit\\framework\\constraint\\isequal' => '/Framework/Constraint/IsEqual.php',
                'phpunit\\framework\\constraint\\isfalse' => '/Framework/Constraint/IsFalse.php',
                'phpunit\\framework\\constraint\\isfinite' => '/Framework/Constraint/IsFinite.php',
                'phpunit\\framework\\constraint\\isidentical' => '/Framework/Constraint/IsIdentical.php',
                'phpunit\\framework\\constraint\\isinfinite' => '/Framework/Constraint/IsInfinite.php',
                'phpunit\\framework\\constraint\\isinstanceof' => '/Framework/Constraint/IsInstanceOf.php',
                'phpunit\\framework\\constraint\\isjson' => '/Framework/Constraint/IsJson.php',
                'phpunit\\framework\\constraint\\isnan' => '/Framework/Constraint/IsNan.php',
                'phpunit\\framework\\constraint\\isnull' => '/Framework/Constraint/IsNull.php',
                'phpunit\\framework\\constraint\\isreadable' => '/Framework/Constraint/IsReadable.php',
                'phpunit\\framework\\constraint\\istrue' => '/Framework/Constraint/IsTrue.php',
                'phpunit\\framework\\constraint\\istype' => '/Framework/Constraint/IsType.php',
                'phpunit\\framework\\constraint\\iswritable' => '/Framework/Constraint/IsWritable.php',
                'phpunit\\framework\\constraint\\jsonmatches' => '/Framework/Constraint/JsonMatches.php',
                'phpunit\\framework\\constraint\\jsonmatcheserrormessageprovider' => '/Framework/Constraint/JsonMatchesErrorMessageProvider.php',
                'phpunit\\framework\\constraint\\lessthan' => '/Framework/Constraint/LessThan.php',
                'phpunit\\framework\\constraint\\logicaland' => '/Framework/Constraint/LogicalAnd.php',
                'phpunit\\framework\\constraint\\logicalnot' => '/Framework/Constraint/LogicalNot.php',
                'phpunit\\framework\\constraint\\logicalor' => '/Framework/Constraint/LogicalOr.php',
                'phpunit\\framework\\constraint\\logicalxor' => '/Framework/Constraint/LogicalXor.php',
                'phpunit\\framework\\constraint\\objecthasattribute' => '/Framework/Constraint/ObjectHasAttribute.php',
                'phpunit\\framework\\constraint\\regularexpression' => '/Framework/Constraint/RegularExpression.php',
                'phpunit\\framework\\constraint\\samesize' => '/Framework/Constraint/SameSize.php',
                'phpunit\\framework\\constraint\\stringcontains' => '/Framework/Constraint/StringContains.php',
                'phpunit\\framework\\constraint\\stringendswith' => '/Framework/Constraint/StringEndsWith.php',
                'phpunit\\framework\\constraint\\stringmatchesformatdescription' => '/Framework/Constraint/StringMatchesFormatDescription.php',
                'phpunit\\framework\\constraint\\stringstartswith' => '/Framework/Constraint/StringStartsWith.php',
                'phpunit\\framework\\constraint\\traversablecontains' => '/Framework/Constraint/TraversableContains.php',
                'phpunit\\framework\\constraint\\traversablecontainsonly' => '/Framework/Constraint/TraversableContainsOnly.php',
                'phpunit\\framework\\coveredcodenotexecutedexception' => '/Framework/CoveredCodeNotExecutedException.php',
                'phpunit\\framework\\dataprovidertestsuite' => '/Framework/DataProviderTestSuite.php',
                'phpunit\\framework\\error\\deprecated' => '/Framework/Error/Deprecated.php',
                'phpunit\\framework\\error\\error' => '/Framework/Error/Error.php',
                'phpunit\\framework\\error\\notice' => '/Framework/Error/Notice.php',
                'phpunit\\framework\\error\\warning' => '/Framework/Error/Warning.php',
                'phpunit\\framework\\exception' => '/Framework/Exception.php',
                'phpunit\\framework\\exceptionwrapper' => '/Framework/ExceptionWrapper.php',
                'phpunit\\framework\\expectationfailedexception' => '/Framework/ExpectationFailedException.php',
                'phpunit\\framework\\incompletetest' => '/Framework/IncompleteTest.php',
                'phpunit\\framework\\incompletetestcase' => '/Framework/IncompleteTestCase.php',
                'phpunit\\framework\\incompletetesterror' => '/Framework/IncompleteTestError.php',
                'phpunit\\framework\\invalidcoverstargetexception' => '/Framework/InvalidCoversTargetException.php',
                'phpunit\\framework\\missingcoversannotationexception' => '/Framework/MissingCoversAnnotationException.php',
                'phpunit\\framework\\outputerror' => '/Framework/OutputError.php',
                'phpunit\\framework\\riskytest' => '/Framework/RiskyTest.php',
                'phpunit\\framework\\riskytesterror' => '/Framework/RiskyTestError.php',
                'phpunit\\framework\\selfdescribing' => '/Framework/SelfDescribing.php',
                'phpunit\\framework\\skippedtest' => '/Framework/SkippedTest.php',
                'phpunit\\framework\\skippedtestcase' => '/Framework/SkippedTestCase.php',
                'phpunit\\framework\\skippedtesterror' => '/Framework/SkippedTestError.php',
                'phpunit\\framework\\skippedtestsuiteerror' => '/Framework/SkippedTestSuiteError.php',
                'phpunit\\framework\\syntheticerror' => '/Framework/SyntheticError.php',
                'phpunit\\framework\\test' => '/Framework/Test.php',
                'phpunit\\framework\\testcase' => '/Framework/TestCase.php',
                'phpunit\\framework\\testfailure' => '/Framework/TestFailure.php',
                'phpunit\\framework\\testlistener' => '/Framework/TestListener.php',
                'phpunit\\framework\\testlistenerdefaultimplementation' => '/Framework/TestListenerDefaultImplementation.php',
                'phpunit\\framework\\testresult' => '/Framework/TestResult.php',
                'phpunit\\framework\\testsuite' => '/Framework/TestSuite.php',
                'phpunit\\framework\\testsuiteiterator' => '/Framework/TestSuiteIterator.php',
                'phpunit\\framework\\unintentionallycoveredcodeerror' => '/Framework/UnintentionallyCoveredCodeError.php',
                'phpunit\\framework\\warning' => '/Framework/Warning.php',
                'phpunit\\framework\\warningtestcase' => '/Framework/WarningTestCase.php',
                'phpunit\\runner\\basetestrunner' => '/Runner/BaseTestRunner.php',
                'phpunit\\runner\\exception' => '/Runner/Exception.php',
                'phpunit\\runner\\filter\\excludegroupfilteriterator' => '/Runner/Filter/ExcludeGroupFilterIterator.php',
                'phpunit\\runner\\filter\\factory' => '/Runner/Filter/Factory.php',
                'phpunit\\runner\\filter\\groupfilteriterator' => '/Runner/Filter/GroupFilterIterator.php',
                'phpunit\\runner\\filter\\includegroupfilteriterator' => '/Runner/Filter/IncludeGroupFilterIterator.php',
                'phpunit\\runner\\filter\\namefilteriterator' => '/Runner/Filter/NameFilterIterator.php',
                'phpunit\\runner\\phpttestcase' => '/Runner/PhptTestCase.php',
                'phpunit\\runner\\standardtestsuiteloader' => '/Runner/StandardTestSuiteLoader.php',
                'phpunit\\runner\\testsuiteloader' => '/Runner/TestSuiteLoader.php',
                'phpunit\\runner\\version' => '/Runner/Version.php',
                'phpunit\\textui\\command' => '/TextUI/Command.php',
                'phpunit\\textui\\resultprinter' => '/TextUI/ResultPrinter.php',
                'phpunit\\textui\\testrunner' => '/TextUI/TestRunner.php',
                'phpunit\\util\\blacklist' => '/Util/Blacklist.php',
                'phpunit\\util\\configuration' => '/Util/Configuration.php',
                'phpunit\\util\\configurationgenerator' => '/Util/ConfigurationGenerator.php',
                'phpunit\\util\\errorhandler' => '/Util/ErrorHandler.php',
                'phpunit\\util\\fileloader' => '/Util/Fileloader.php',
                'phpunit\\util\\filesystem' => '/Util/Filesystem.php',
                'phpunit\\util\\filter' => '/Util/Filter.php',
                'phpunit\\util\\getopt' => '/Util/Getopt.php',
                'phpunit\\util\\globalstate' => '/Util/GlobalState.php',
                'phpunit\\util\\invalidargumenthelper' => '/Util/InvalidArgumentHelper.php',
                'phpunit\\util\\json' => '/Util/Json.php',
                'phpunit\\util\\log\\junit' => '/Util/Log/JUnit.php',
                'phpunit\\util\\log\\teamcity' => '/Util/Log/TeamCity.php',
                'phpunit\\util\\php\\abstractphpprocess' => '/Util/PHP/AbstractPhpProcess.php',
                'phpunit\\util\\php\\defaultphpprocess' => '/Util/PHP/DefaultPhpProcess.php',
                'phpunit\\util\\php\\windowsphpprocess' => '/Util/PHP/WindowsPhpProcess.php',
                'phpunit\\util\\printer' => '/Util/Printer.php',
                'phpunit\\util\\regularexpression' => '/Util/RegularExpression.php',
                'phpunit\\util\\test' => '/Util/Test.php',
                'phpunit\\util\\testdox\\htmlresultprinter' => '/Util/TestDox/HtmlResultPrinter.php',
                'phpunit\\util\\testdox\\nameprettifier' => '/Util/TestDox/NamePrettifier.php',
                'phpunit\\util\\testdox\\resultprinter' => '/Util/TestDox/ResultPrinter.php',
                'phpunit\\util\\testdox\\textresultprinter' => '/Util/TestDox/TextResultPrinter.php',
                'phpunit\\util\\testdox\\xmlresultprinter' => '/Util/TestDox/XmlResultPrinter.php',
                'phpunit\\util\\texttestlistrenderer' => '/Util/TextTestListRenderer.php',
                'phpunit\\util\\type' => '/Util/Type.php',
                'phpunit\\util\\xml' => '/Util/Xml.php',
                'phpunit\\util\\xmltestlistrenderer' => '/Util/XmlTestListRenderer.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd

if (stream_resolve_include_path('PHP/Invoker/Autoload.php')) {
    require_once 'PHP/Invoker/Autoload.php';
}

if (stream_resolve_include_path('PHPUnit/DbUnit/autoload.php')) {
    require_once 'PHPUnit/DbUnit/autoload.php';
}
